config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "splash#index"
  resources :groups, only: [:index, :show, :new, :create] do
    resources :products, only: [:new, :create]    
  end
  
 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :products
  validates :name, presence: true
  validates :icon, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups
  validates :name, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, foreign_key: 'author_id'
  has_many :groups, foreign_key: 'author_id'
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def show
    @group = current_user.groups.find(params[:id])
    @products = @group.products.order(created_at: :asc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'Category Successfully Created'
    else
      flash.now[:alert] = @group.errors.full_messages[0]
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @group = current_user.groups.find(params[:group_id])
    @product = Product.new
  end

  def create
    @group = current_user.groups.find(params[:group_id])
    @product = current_user.products.new(product_params)
    if @product.save
      redirect_to group_path(@group), notice: 'Transaction Added Successfully'
    else
      render :new
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]
  def index
    return unless user_signed_in?

    redirect_to groups_path
  end
end

app/views/groups/index.html.erb
<% content_for :back_path, root_path%>
<% content_for :page_name, "Groups" %>
<% content_for :nav_button do %>
  <%= button_to destroy_user_session_path, class:'logout-btn', method: :delete do %>
    <i class="fas fa-sign-out-alt icon-white"></i> Logout
  <% end %>
<% end %>
<div class='group-container'>
  <ul class='group-list'>
    <% @groups.each do |group| %>
      <li class='group-list-item'>
        <%= link_to group do %>
          <%= render "shared/group", group: group %>
        <% end %>
       </li>
    <% end %>
  </ul>
  <%= button_to "Add Group", new_group_path, method: :get %>
</div>

app/views/groups/new.html.erb
<% content_for :back_path, root_path %>
<% content_for :page_name, "Create Group" %>
<% content_for :nav_button do %>
  <%= button_to destroy_user_session_path, class:'logout-btn', method: :delete do %>
    <i class="fas fa-sign-out-alt icon-white"></i> Logout
  <% end %>
<% end %>
<div class='new-group'>
  <%= form_with(model: @group) do |form| %>
    <h1> New Group </h1>
    <div>
      <%= form.text_field :icon, placeholder: 'Link to icon', required: true, pattern: "^(http|https)://[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,}(\/.*)?$" %>
    </div>
    <div>
      <%= form.text_field :name, placeholder: 'Name of group', required: true %>
    </div>
    <%= form.submit "Create", class: 'submit-btn' %>
  <% end %>
</div>

app/views/groups/show.html.erb
<% content_for :back_path, root_path %>
<% content_for :page_name, "Transactions" %>
<% content_for :nav_button do %>
  <%= button_to destroy_user_session_path, class:'logout-btn', method: :delete do %>
    <i class="fas fa-sign-out-alt icon-white"></i> Logout
  <% end %>
<% end %>
<ul class='transaction-list'>
  <li class='group-transactions'>
    <%= render "shared/group", group: @group %>
  </li>
    <% @products.each do |product| %>
      <li class='transaction-details'>
        <div>
          <h2>Product Name: <%= product.name %> </h2>
          <p>Amount: $<%= product.amount %> </p>
        </div>
        <p>Created at: <%= product.created_at.strftime('%d %b %Y at %l:%M %P') %> </p>
      </li>
    <% end %>
  <%= button_to 'Add Transaction', new_group_product_path(@group), method: :get %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FrugalFunds</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <%= render "shared/navbar" %>   
    </header>
    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/products/new.html.erb
<% content_for :back_path, root_path %>
<% content_for :page_name, "New Transactions" %>
<% content_for :nav_button do %>
  <%= button_to destroy_user_session_path, class:'logout-btn', method: :delete do %>
    <i class="fas fa-sign-out-alt icon-white"></i> Logout
  <% end %>
<% end %>
<div class="new-transaction">
  <%= form_with(model: ([@group, @product])) do |form| %>
    <h1>Create Transaction</h1>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name, required: true %>
    </div>
    <div>
      <%= form.label :amount %>
      <%= form.number_field :amount, required: true, min: 1 %>
    </div>
    <div>
      <%= form.label "Group" %>
      <%= form.collection_select :group_ids, current_user.groups, :id, :name, {}, { multiple: true, required: true } %>
    </div>
    <%= form.submit "Create", class: 'submit-btn' %>
  <% end %>
</div>

app/views/shared/_group.html.erb
<div>
  <div>
    <%= image_tag group.icon, alt: group.name %>
    <h2><%= group.name %></h2>  
  </div>
  <div>
    <p><%= group.created_at.strftime('%d %b %Y') %></p>
    <p><%= group.products.sum {|product|product[:amount]} %></p>  
  </div>
</div>

app/views/shared/_navbar.html.erb
<% unless content_for?(:nav_bar) %>
  <nav>
    <% if content_for?(:page_name) %>
      <%= link_to yield(:back_path) do %>
        <i class="fas fa-arrow-left icon-white"></i>
      <% end %>
    <% end %>

    <% if content_for?(:page_name) %>  
      <div>
        <span class='page-name'> <%= yield(:page_name) %> </span>
      </div>
    <% end %>

    <% if content_for?(:nav_button) %>
      <%= yield(:nav_button) %>
    <% end %>
  </nav>
<% end %>

app/views/splash/index.html.erb
<% content_for :nav_bar, 'navbar not required' %>
<div class='splash-container'>
  <h1>Welcome to Frugal Funds!!</h1>
  <div class='splash-authentication'>
    <%= link_to "Log in", new_user_session_path %>
    <%= link_to "Sign up", new_user_registration_path %>  
  </div>
</div>